name: Feature Request
description: Suggest a new feature for the bgce-bot MVP
title: '[Feature] bgce-bot - '
labels: ['enhancement', 'mvp']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature for bgce-bot! Please provide clear details to help us prioritize and implement it.
  - type: input
    id: feature-title
    attributes:
      label: Feature Title
      placeholder: e.g., "Chatbot links PRs and issues"
    validations:
      required: true
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Describe the feature and why it’s needed.
      placeholder: |
        What does this feature do? e.g., "Chatbot links PRs and issues"
        Why is it needed? e.g., "Manual issue tracking slows collaboration"
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How critical is this feature for the MVP?
      options:
        - Must-Have (v0.1)
        - Should-Have (Post-MVP)
        - Could-Have (Nice-to-Have)
        - Won't-Have (Out of Scope)
      default: 2
    validations:
      required: true